### ISSUE TITLE
mon hiding under nonexistent obj (fmon)

### ISSUE THREAD

**Issue by elunna** [elunna/NerfHack#27]
```
Suddenly, the dungeon collapses.
mon hiding under nonexistent obj (fmon)
  Generating more information you may report:
  
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff71fa859 in __GI_abort () at abort.c:79
#2  0x0000555555962994 in NH_abort (why=0x7fffffffd8a0 "mon hiding under nonexistent obj (fmon)")
    at end.c:227
#3  0x00005555559676c7 in panic (str=0x555556091f00 "%s") at end.c:1134
#4  0x0000555555c27d59 in impossible (s=0x55555602f640 "mon hiding under nonexistent obj (%s)")
    at pline.c:591
#5  0x0000555555ad5cad in sanity_check_single_mon (mtmp=0x6110002ccf80, chk_geno=1 '\001',
    msg=0x55555602fb80 "fmon") at mon.c:153
#6  0x0000555555ad679e in mon_sanity_check () at mon.c:223
#7  0x000055555581c7ec in sanity_check () at cmd.c:4510
#8  0x000055555577bb41 in moveloop_core () at allmain.c:183
#9  0x000055555577e464 in moveloop (resuming=0 '\000') at allmain.c:556
#10 0x0000555555ec0fc4 in main (argc=4, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:313

 mnum = 109, cave spider
 
 (gdb) p gt.toplines
$2 = "You are now hiding on the ceiling.  You fall from the ceiling!", '\000' <repeats 237 times>

mattacku(struct monst *mtmp)

Most likely scenario: Hero polymorphed into a piercer and gets hit, falls from the ceiling (which counts as hiding) and the mundetected flag doesn't get unset.
```

**Comment by elunna** [comment]
Actually - looks like our u.uundetected was correctly set back to 0 after dropping from the ceiling.

I think what is happening is that a cave spider that is hidden attacks us while we are hiding on the ceiling (as a piercer), we drop on the spider and hit it, it gets moved as part of the piercer hitting logic.

I tested this as a piercer, but it didn't result in the error. So I switched to a lurker above and it popped up right away.
