### ISSUE TITLE
objdescr_is: null obj (in grease trap)

### ISSUE THREAD

**Issue by elunna** [elunna/NerfHack#37]
```
Suddenly, the dungeon collapses.
objdescr_is: null obj
  Generating more information you may report:

[00] /lib/x86_64-linux-gnu/libasan.so.6(+0x45c0e) [0x7ffff7603c0e]
[01] /home/user/games/nerfhackdir/nerfhack(NH_panictrace_libc+0xf9) [0x555555ce656e]
[02] /home/user/games/nerfhackdir/nerfhack(NH_abort+0xfa) [0x555555996d40]
[03] /home/user/games/nerfhackdir/nerfhack(panic+0x6a6) [0x55555598bf2e]
[04] /home/user/games/nerfhackdir/nerfhack(impossible+0x2ee) [0x555555c6b2f8]
[05] /home/user/games/nerfhackdir/nerfhack(objdescr_is+0x2f) [0x555555bbedd3]
[06] /home/user/games/nerfhackdir/nerfhack(trapeffect_grease_trap+0x3d8) [0x555555e009a8]
[07] /home/user/games/nerfhackdir/nerfhack(trapeffect_selector+0x15c) [0x555555e0d916]
[08] /home/user/games/nerfhackdir/nerfhack(dotrap+0x794) [0x555555e0e2f8]
[09] /home/user/games/nerfhackdir/nerfhack(spoteffects+0x9df) [0x555555a01a30]
[10] /home/user/games/nerfhackdir/nerfhack(domove_core+0x3861) [0x5555559fe14b]
[11] /home/user/games/nerfhackdir/nerfhack(domove+0xc2) [0x5555559fa76e]
[12] /home/user/games/nerfhackdir/nerfhack(rhack+0xe19) [0x555555849112]
[13] /home/user/games/nerfhackdir/nerfhack(moveloop_core+0x26dd) [0x5555557ae190]
[14] /home/user/games/nerfhackdir/nerfhack(moveloop+0x21) [0x5555557ae68e]
[15] /home/user/games/nerfhackdir/nerfhack(main+0xb07) [0x555555f25c24]
[16] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7ffff7269d90]
[17] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7ffff7269e40]
[18] /home/user/games/nerfhackdir/nerfhack(_start+0x25) [0x5555557ab175]

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339570112)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737339570112, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7282476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff72687f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555996d66 in NH_abort (why=0x7fffffffce20 "objdescr_is: null obj") at end.c:1959
#6  0x000055555598bf2e in panic (str=0x55555610e1a0 "%s") at end.c:468
#7  0x0000555555c6b2f8 in impossible (s=0x5555560d8400 "objdescr_is: null obj") at pline.c:609
#8  0x0000555555bbedd3 in objdescr_is (obj=0x0, descr=0x555556173700 "mud boots") at o_init.c:358
#9  0x0000555555e009a8 in trapeffect_grease_trap (mtmp=0x555556450d48 <gy+8>, trap=0x603000641590, 
    trflags=0) at trap.c:1810
#10 0x0000555555e0d916 in trapeffect_selector (mtmp=0x555556450d48 <gy+8>, trap=0x603000641590, 
    trflags=0) at trap.c:3495
#11 0x0000555555e0e2f8 in dotrap (trap=0x603000641590, trflags=0) at trap.c:3604
#12 0x0000555555a01a30 in spoteffects (pick=1 '\001') at hack.c:3142
#13 0x00005555559fe14b in domove_core () at hack.c:2824
#14 0x00005555559fa76e in domove () at hack.c:2516
#15 0x0000555555849112 in rhack (key=54) at cmd.c:3457
#16 0x00005555557ae190 in moveloop_core () at allmain.c:535
#17 0x00005555557ae68e in moveloop (resuming=0 '\000') at allmain.c:566
#18 0x0000555555f25c24 in main (argc=4, argv=0x7fffffffdf38) at ../sys/unix/unixmain.c:323
```

**Comment by elunna** [comment]
Fixed in bbfce6e6d
