### ISSUE TITLE
breaking odd object (336)?

### ISSUE THREAD

**Issue by elunna** [elunna/NerfHack#41]
```
Suddenly, the dungeon collapses.
breaking odd object (336)?
  Generating more information you may report:

[00] /lib/x86_64-linux-gnu/libasan.so.6(+0x45c0e) [0x7ffff7603c0e]
[01] /home/user/games/nerfhackdir/nerfhack(NH_panictrace_libc+0xf9) [0x555555cacef0]
[02] /home/user/games/nerfhackdir/nerfhack(NH_abort+0xfa) [0x55555597445a]
[03] /home/user/games/nerfhackdir/nerfhack(panic+0x6a1) [0x5555559696e1]
[04] /home/user/games/nerfhackdir/nerfhack(impossible+0x2d9) [0x555555c32b0a]
[05] /home/user/games/nerfhackdir/nerfhack(+0x3d4ad6) [0x555555928ad6]
[06] /home/user/games/nerfhackdir/nerfhack(throwit+0x7131) [0x55555591feb5]
[07] /home/user/games/nerfhackdir/nerfhack(+0x3b75b7) [0x55555590b5b7]
[08] /home/user/games/nerfhackdir/nerfhack(dofire+0x1a4c) [0x55555590f45b]
[09] /home/user/games/nerfhackdir/nerfhack(rhack+0xa90) [0x555555829b0a]
[10] /home/user/games/nerfhackdir/nerfhack(moveloop_core+0x272f) [0x555555790185]
[11] /home/user/games/nerfhackdir/nerfhack(moveloop+0x21) [0x555555790683]
[12] /home/user/games/nerfhackdir/nerfhack(main+0xaf1) [0x555555eeb6f4]
[13] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7ffff7269d90]
[14] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7ffff7269e40]
[15] /home/user/games/nerfhackdir/nerfhack(_start+0x25) [0x55555578d115]

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737339570112, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7282476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff72687f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555974480 in NH_abort (why=0x7fffffffcf00 "breaking odd object (336)?") at end.c:1975
#6  0x00005555559696e1 in panic (str=0x5555560c61e0 "%s") at end.c:490
#7  0x0000555555c32b0a in impossible (s=0x555555ffeea0 "breaking odd object (%d)?") at pline.c:597
#8  0x0000555555928ad6 in breakmsg (obj=0x60b0000073c0, in_view=1 '\001') at dothrow.c:2692
#9  0x000055555591feb5 in throwit (obj=0x60b0000073c0, wep_mask=512, twoweap=0 '\000', oldslot=0x0) at dothrow.c:1796
#10 0x000055555590b5b7 in throw_obj (obj=0x0, shotlimit=0) at dothrow.c:273
#11 0x000055555590f45b in dofire () at dothrow.c:581
#12 0x0000555555829b0a in rhack (key=102) at cmd.c:3371
#13 0x0000555555790185 in moveloop_core () at allmain.c:535
#14 0x0000555555790683 in moveloop (resuming=0 '\000') at allmain.c:566
#15 0x0000555555eeb6f4 in main (argc=4, argv=0x7fffffffdf68) at ../sys/unix/unixmain.c:313
(gdb) p bt.toplines
No symbol "bt" in current context.
(gdb) p toplines
No symbol "toplines" in current context.
(gdb) p gt.toplines
$1 = "In what direction? J", '\000' <repeats 279 times>
(gdb) up
#1  __pthread_kill_internal (signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:78
78	in ./nptl/pthread_kill.c
(gdb) 
#2  __GI___pthread_kill (threadid=140737339570112, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
89	in ./nptl/pthread_kill.c
(gdb) 
#3  0x00007ffff7282476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
26	../sysdeps/posix/raise.c: No such file or directory.
(gdb) 
#4  0x00007ffff72687f3 in __GI_abort () at ./stdlib/abort.c:79
79	./stdlib/abort.c: No such file or directory.
(gdb) 
#5  0x0000555555974480 in NH_abort (why=0x7fffffffcf00 "breaking odd object (336)?") at end.c:1975
1975	    NH_abort_;
(gdb) 
#6  0x00005555559696e1 in panic (str=0x5555560c61e0 "%s") at end.c:490
490	        NH_abort(buf); /* generate core dump */
(gdb) 
#7  0x0000555555c32b0a in impossible (s=0x555555ffeea0 "breaking odd object (%d)?") at pline.c:597
597	        panic("%s", pbuf);
(gdb) 
#8  0x0000555555928ad6 in breakmsg (obj=0x60b0000073c0, in_view=1 '\001') at dothrow.c:2692
2692	            impossible("breaking odd object (%d)?", obj->otyp);
(gdb) 
#9  0x000055555591feb5 in throwit (obj=0x60b0000073c0, wep_mask=512, twoweap=0 '\000', oldslot=0x0) at dothrow.c:1796
1796	            breakmsg(obj, cansee(gb.bhitpos.x, gb.bhitpos.y));
(gdb) p *obj
$2 = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, cobj = 0x0, o_id = 7, ox = 0, oy = 0, otyp = 336, owt = 20, quan = 1, spe = 0 '\000', oclass = 7 '\a', invlet = 100 'd', 
  oartifact = 0 '\000', where = 0 '\000', timed = 0, cursed = 0, blessed = 0, unpaid = 0, no_charge = 0, known = 1, dknown = 1, bknown = 1, rknown = 1, oeroded = 0, oeroded2 = 0, oerodeproof = 0, olocked = 0, 
  obroken = 0, otrapped = 0, recharged = 0, lamplit = 0, globby = 0, greased = 0, nomerge = 0, how_lost = 1, in_use = 0, bypass = 0, cknown = 0, lknown = 0, pickup_prev = 0, ghostly = 0, corpsenm = -1, usecount = 0, 
  oeaten = 0, age = 1, owornmask = 0, lua_ref_cnt = 0, omigr_from_dnum = 0, omigr_from_dlevel = 0, oextra = 0x0}
(gdb) Quit
(gdb) p gm.moves
$3 = 534
```

**Comment by elunna** [comment]
POT_VAMPIRE_BLOOD ?

**Comment by elunna** [comment]
Haven't seen this in a long while. Stale.
