### ISSUE TITLE
Cannot open record file!

### ISSUE THREAD

**Issue by elunna** [elunna/NerfHack#47]
```
Suddenly, the dungeon collapses.
Cannot open record file!
  Generating more information you may report:

[00] /lib/x86_64-linux-gnu/libasan.so.6(+0x45c0e) [0x7ffff7603c0e]
[01] /home/user/games/nerfhackdir/nerfhack(NH_panictrace_libc+0xf9) [0x555555d236bd]
[02] /home/user/games/nerfhackdir/nerfhack(NH_abort+0xfa) [0x5555559b331f]
[03] /home/user/games/nerfhackdir/nerfhack(panic+0x6c6) [0x5555559a84eb]
[04] /home/user/games/nerfhackdir/nerfhack(impossible+0x2ee) [0x555555ca02ca]
[05] /home/user/games/nerfhackdir/nerfhack(get_rnd_toptenentry+0x49) [0x555555e30849]
[06] /home/user/games/nerfhackdir/nerfhack(tt_doppel+0x23) [0x555555e30b08]
[07] /home/user/games/nerfhackdir/nerfhack(select_newcham_form+0x194) [0x555555b5f4c3]
[08] /home/user/games/nerfhackdir/nerfhack(newcham+0x654) [0x555555b607a7]
[09] /home/user/games/nerfhackdir/nerfhack(makemon+0x2a67) [0x555555a99fcb]
[10] /home/user/games/nerfhackdir/nerfhack(moveloop_core+0x493) [0x5555557b6f51]
[11] /home/user/games/nerfhackdir/nerfhack(moveloop+0x21) [0x5555557b98a5]
[12] /home/user/games/nerfhackdir/nerfhack(main+0xb2b) [0x555555f7129f]
[13] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7ffff7269d90]
[14] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7ffff7269e40]
[15] /home/user/games/nerfhackdir/nerfhack(_start+0x25) [0x5555557b6175]

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737339570112, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7282476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff72687f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00005555559b3345 in NH_abort (why=0x7fffffffc9d0 "Cannot open record file!") at end.c:1961
#6  0x00005555559a84eb in panic (str=0x555556160900 "%s") at end.c:470
#7  0x0000555555ca02ca in impossible (s=0x5555561c43a0 "Cannot open record file!") at pline.c:608
#8  0x0000555555e30849 in get_rnd_toptenentry () at topten.c:1386
DW_FORM_addr_index used without .debug_addr section [in module /home/user/games/nerfhackdir/nerfhack]
```

**Comment by elunna** [comment]
Fixed in 50e79528c
