### ISSUE TITLE
no monster to remove (mon zapping cursed wand which explodes)

### ISSUE THREAD

**Issue by elunna** [elunna/NerfHack#48]
```
Suddenly, the dungeon collapses.
no monster to remove
  Generating more information you may report:

[00] /lib/x86_64-linux-gnu/libasan.so.6(+0x45c0e) [0x7ffff7603c0e]
[01] /home/user/games/nerfhackdir/nerfhack(NH_panictrace_libc+0xf9) [0x555555d237bf]
[02] /home/user/games/nerfhackdir/nerfhack(NH_abort+0xfa) [0x5555559b331f]
[03] /home/user/games/nerfhackdir/nerfhack(panic+0x6c6) [0x5555559a84eb]
[04] /home/user/games/nerfhackdir/nerfhack(impossible+0x2ee) [0x555555ca03cc]
[05] /home/user/games/nerfhackdir/nerfhack(m_move+0x4b57) [0x555555b8a46d]
[06] /home/user/games/nerfhackdir/nerfhack(dochug+0x2f75) [0x555555b7d0b3]
[07] /home/user/games/nerfhackdir/nerfhack(dochugw+0x11a) [0x555555b756dc]
[08] /home/user/games/nerfhackdir/nerfhack(movemon_singlemon+0xef8) [0x555555b3acea]
[09] /home/user/games/nerfhackdir/nerfhack(iter_mons_safe+0x18c) [0x555555b5a107]
[10] /home/user/games/nerfhackdir/nerfhack(movemon+0x55) [0x555555b3ad46]
[11] /home/user/games/nerfhackdir/nerfhack(moveloop_core+0x23e) [0x5555557b6cfc]
[12] /home/user/games/nerfhackdir/nerfhack(moveloop+0x21) [0x5555557b98a5]
[13] /home/user/games/nerfhackdir/nerfhack(main+0xb2b) [0x555555f713ed]
[14] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7ffff7269d90]
[15] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7ffff7269e40]
[16] /home/user/games/nerfhackdir/nerfhack(_start+0x25) [0x5555557b6175]

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) p gt.toplines
$1 = "You see here a lock pick (for sale, 20 zorkmids).  The goblin zaps a tin wand, which suddenly explodes!  Boom!  The goblin is caught in the magical blast!  The goblin is killed!  The small mimic is ca"...
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737339570112) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737339570112, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7282476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff72687f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00005555559b3345 in NH_abort (why=0x7fffffffce70 "no monster to remove") at end.c:1961
#6  0x00005555559a84eb in panic (str=0x555556160900 "%s") at end.c:470
#7  0x0000555555ca03cc in impossible (s=0x555556100760 "no monster to remove") at pline.c:608
#8  0x0000555555b8a46d in m_move (mtmp=0x61100036f280, after=0) at monmove.c:2110
#9  0x0000555555b7d0b3 in dochug (mtmp=0x61100036f280) at monmove.c:943
#10 0x0000555555b756dc in dochugw (mtmp=0x61100036f280, chug=1 '\001') at monmove.c:220
#11 0x0000555555b3acea in movemon_singlemon (mtmp=0x61100036f280) at mon.c:1665
#12 0x0000555555b5a107 in iter_mons_safe (bfunc=0x555555b39df2 <movemon_singlemon>) at mon.c:5083
#13 0x0000555555b3ad46 in movemon () at mon.c:1675
#14 0x00005555557b6cfc in moveloop_core () at allmain.c:196
#15 0x00005555557b98a5 in moveloop (resuming=0 '\000') at allmain.c:576
#16 0x0000555555f713ed in main (argc=4, argv=0x7fffffffdf38) at ../sys/unix/unixmain.c:323
```

**Comment by elunna** [comment]
I believe this was caused by monster zapping a cursed wand, which then explodes and kills the monster. There should be a different return value of 1 if the monster dies when this happens. I missed this when porting the behavior from SLASH'EM. Fixed in e2a9c237f
