### ISSUE TITLE
Memory leak: restobjchn

### ISSUE THREAD

**Issue by elunna** [elunna/NerfHack#59]
```
=================================================================
==4129==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0x7fa07e8dd887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5567c21c598e in alloc ../src/alloc.c:73
    #2 0x5567c2742785 in restobjchn /home/user/Documents/dev/NerfHack/src/restore.c:252
    #3 0x5567c274437b in restmonchn /home/user/Documents/dev/NerfHack/src/restore.c:417
    #4 0x5567c2749147 in getlev /home/user/Documents/dev/NerfHack/src/restore.c:1091
    #5 0x5567c22ed595 in goto_level /home/user/Documents/dev/NerfHack/src/do.c:1741
    #6 0x5567c237e74d in next_level /home/user/Documents/dev/NerfHack/src/dungeon.c:1511
    #7 0x5567c22ea758 in dodown /home/user/Documents/dev/NerfHack/src/do.c:1366
    #8 0x5567c22664d7 in rhack /home/user/Documents/dev/NerfHack/src/cmd.c:3435
    #9 0x5567c21c0559 in moveloop_core /home/user/Documents/dev/NerfHack/src/allmain.c:554
    #10 0x5567c21c0a57 in moveloop /home/user/Documents/dev/NerfHack/src/allmain.c:585
    #11 0x5567c29991c4 in main ../sys/unix/unixmain.c:323
    #12 0x7fa07e4d4d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 104 byte(s) leaked in 1 allocation(s).
```

**Comment by elunna** [comment]
Stale.

**Comment by elunna** [comment]
Likely related to 4e5bdc9c1. Closing for now.
