### ISSUE TITLE
Memory leak: l_selection_room

### ISSUE THREAD

**Issue by elunna** [elunna/NerfHack#60]
```
=================================================================
==285340==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1688 byte(s) in 1 object(s) allocated from:
    #0 0x7f97ceee8887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x564e0cefc98e in alloc ../src/alloc.c:73
    #2 0x564e0cefcaef in dupstr ../src/alloc.c:238
    #3 0x564e0d32cc82 in l_selection_push_copy /home/user/Documents/dev/NerfHack/src/nhlsel.c:120
    #4 0x564e0d32f795 in l_selection_room /home/user/Documents/dev/NerfHack/src/nhlsel.c:445
    #5 0x564e0d72b074 in luaD_precall (/home/user/games/nerfhackdir/nerfhack+0xaa5074)

SUMMARY: AddressSanitizer: 1688 byte(s) leaked in 1 allocation(s).
```

**Comment by elunna** [comment]
Stale.
