### ISSUE TITLE
ceiling hider hiding in solid stone (fmon)

### ISSUE THREAD

**Issue by elunna** [elunna/NerfHack#64]
```
Suddenly, the dungeon collapses.
ceiling hider hiding in solid stone (fmon)
  Generating more information you may report:

(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350112640) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737350112640) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737350112640, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c6c476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c527f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00005555556a3755 in NH_abort (why=0x7fffffffd3b0 "ceiling hider hiding in solid stone (fmon)") at end.c:1965
#6  0x000055555569f233 in panic (str=0x5555559c55ed "%s") at end.c:470
#7  0x00005555557dece7 in impossible (s=0x5555559afc9f "ceiling hider hiding %s (%s)") at pline.c:608
#8  0x0000555555745427 in sanity_check_single_mon (mtmp=0x5555569f8e60, chk_geno=1 '\001', msg=0x5555559afe02 "fmon")
    at mon.c:195
#9  0x0000555555745704 in mon_sanity_check () at mon.c:267
#10 0x00005555558daf60 in sanity_check () at wizcmds.c:1464
#11 0x00005555555d9159 in moveloop_core () at allmain.c:185
#12 0x00005555555da046 in moveloop (resuming=0 '\000') at allmain.c:585
#13 0x00005555558ffbf6 in main (argc=4, argv=0x7fffffffdf18) at ../sys/unix/unixmain.c:323

(gdb) p gt.toplines
$1 = "You materialize on a different level!  You remember this level as \\b\353.", '\000' <repeats 229 times>

(gdb) p *mtmp
$2 = {nmon = 0x555556575880, data = 0x555555b0a360 <mons+29792>, m_id = 6894940, mnum = 266, cham = -1, movement = 12, 
  m_lev = 9 '\t', malign = 5 '\005', mx = 21, my = 13, mux = 39, muy = 18, mtrack = {{x = 0, y = 0}, {x = 0, y = 0}, {x = 0, 
      y = 0}, {x = 0, y = 0}}, mhp = 48, mhpmax = 48, mappearance = 0, m_ap_type = 0 '\000', mtame = 0 '\000', 
  mintrinsics = 0, mextrinsics = 0, seen_resistance = 0, mspec_used = 0, female = 1, minvis = 0, invis_blkd = 0, 
  perminvis = 0, mcan = 0, mburied = 0, mundetected = 1, mcansee = 1, mspeed = 0, permspeed = 0, mrevived = 0, mcloned = 0, 
  mavenge = 0, mflee = 0, mfleetim = 0, msleeping = 0, mblinded = 0, mstun = 0, mfrozen = 0, mcanmove = 1, mconf = 0, 
  mdiseased = 0, mdiseabyu = 0, mpeaceful = 0, mtrapped = 0, mleashed = 0, isshk = 0, isminion = 0, isgd = 0, ispriest = 0, 
  iscerberus = 0, iswiz = 0, wormno = 0, mtemplit = 0, meverseen = 1, mwither_from_u = 0, mberserk = 0, mrabid = 0, 
  mspotted = 0, mwither = 0 '\000', mstrategy = 0, mtrapseen = 0, mlstmv = 7445014, mstate = 0, migflags = 0, mspare1 = 0, 
  minvent = 0x0, mw = 0x0, misc_worn_check = 536870912, weapon_check = 0, former_rank = '\000' <repeats 24 times>, 
  meating = 0, msummoned = 0, mdiseasetime = 0, mreflecttime = 0, mphasetime = 0, mprotection = 0 '\000', 
  mprottime = 0 '\000', mextra = 0x0}
(gdb) 

GREEN SLIME.


(gdb) p svl.level.locations[21][13]
$3 = {glyph = 5719, typ = 23 '\027', seenv = 255 '\377', splatpm = 0, flags = 8, horizontal = 1, lit = 1, waslit = 0, 
  roomno = 0, edge = 0, candig = 0}

Green slime hiding on closed door.
```

**Comment by elunna** [comment]
This seems to be a case where a green slime gets hidden on a closed door. I'm trying to reproduce it but so far unsuccessful:
* Spawned a hiding green slime on an open room wall, tried zapping a wand of locking but it's blocked.
* Spawned a hiding green slime on an open door, but I cannot close the door or lock it with a wand of locking.

Maybe it first oozes under the door, then hides on the closed door. I lured a green slime to ooze under a door then trapped it in with boulders, but it didn't seem to want to hide even after many turns.

I caught some similar stuff before this where a rock piercer also trigger the same error, so not sure if it's the same problem or not.

**Comment by elunna** [comment]
Stale.
