### ISSUE TITLE
getdir: command queue had no dir?

### ISSUE THREAD

**Issue by elunna** [elunna/NerfHack#8]
Found while fuzzing

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff71fa859 in __GI_abort () at abort.c:79
#2  0x00005555559396df in NH_abort (why=0x7fffffffd3b0 "getdir: command queue had no dir?")
    at end.c:212
#3  0x000055555593c410 in panic (str=0x55555601a340 "%s") at end.c:946
#4  0x0000555555bdc877 in impossible (s=0x555555f0eb40 "getdir: command queue had no dir?")
    at pline.c:532
#5  0x0000555555800295 in getdir (s=0x0) at cmd.c:5243
#6  0x00005555558ddf2f in throw_obj (obj=0x60b00069bff0, shotlimit=0) at dothrow.c:95
#7  0x00005555558e3bfc in dofire () at dothrow.c:572
#8  0x00005555557febb5 in rhack (cmd=0x0) at cmd.c:5007
#9  0x00005555557ef5d5 in do_repeat () at cmd.c:2520
#10 0x00005555557febb5 in rhack (cmd=0x55555632691c <gc+2332> "\001") at cmd.c:5007
#11 0x0000555555765e52 in moveloop_core () at allmain.c:521
#12 0x0000555555766406 in moveloop (resuming=0 '\000') at allmain.c:574
#13 0x0000555555e5d2a2 in main (argc=4, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:310
```
(gdb) p gt.toplines
$2 = "For some reason, you cannot throw the stone!", '\000' <repeats 255 times>

**Comment by elunna** [comment]
The obj in question:
```

(gdb) p *obj
$3 = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, cobj = 0x0,
  o_id = 2849759, ox = 11, oy = 3, otyp = 470, owt = 500, quan = 1, spe = 0 '\000',
  oclass = 13 '\r', invlet = 98 'b', oartifact = 0 '\000', where = 3 '\003', timed = 0,
  cursed = 1, blessed = 0, unpaid = 0, no_charge = 0, known = 1, dknown = 1, bknown = 1,
  rknown = 0, oeroded = 0, oeroded2 = 0, oerodeproof = 0, olocked = 0, obroken = 0,
  otrapped = 0, recharged = 0, lamplit = 0, globby = 0, greased = 0, nomerge = 0, how_lost = 0,
  in_use = 0, bypass = 0, cknown = 0, lknown = 0, pickup_prev = 0, ghostly = 0, corpsenm = 0,
  usecount = 0, oeaten = 0, age = 2151690, owornmask = 512, lua_ref_cnt = 0,
  omigr_from_dnum = 0, omigr_from_dlevel = 0, oextra = 0x60300079f420}
(gdb)
```
